/**
 * The six learning tracks, used by both the mobile menu ("Jalur Belajar" list +
 * per-course modules) and the mobile search overlay (keyword match + the
 * "Level · duration · modules" result meta). "AI Fundamentals" modules mirror
 * the LESSONS list in Foundation.jsx; the rest are outlined pending real content.
 */
export const MENU_COURSES = [
  {
    level: "Level 01",
    title: "AI Fundamentals",
    duration: "±3,5 jam",
    moduleCount: 7,
    lessonCount: 21,
    keywords: [
      "AI",
      "artificial intelligence",
      "pemula",
      "dasar",
      "belajar AI",
      "mulai",
      "fondasi",
      "cara kerja AI",
      "LLM",
      "large language model",
      "ChatGPT",
      "prompting",
      "prompt",
      "cara nulis prompt",
      "tools AI",
      "aplikasi AI",
      "AI di tempat kerja",
      "produktivitas",
      "efisiensi",
      "rangkum",
      "rangkum dokumen",
      "bikin draft",
      "notulen",
      "notulen rapat",
      "keamanan AI",
      "etika AI",
      "AI yang aman",
      "roadmap",
      "jalur belajar",
    ],
    modules: [
      "Halo, Kenalin Aku AI",
      "Cara AI Berpikir",
      "Bahasa AI: Prompting 101",
      "AI di Dunia Kerja & Keseharian",
      "Tools AI: Pilih Yang Cocok",
      "Pakai AI dengan Aman & Bijak",
      "Roadmap: Kamu Sudah Siap",
    ],
  },
  {
    level: "Level 02",
    title: "AI Tools for You",
    duration: "±3,5 jam",
    moduleCount: 7,
    lessonCount: 21,
    keywords: [
      "tools AI",
      "aplikasi AI",
      "pilih tools",
      "rekomendasi tools",
      "tools terbaik",
      "ChatGPT",
      "Perplexity",
      "Notion AI",
      "Midjourney",
      "tools untuk menulis",
      "tools untuk desain",
      "tools untuk kerja",
      "tools untuk produktivitas",
      "tools gratis",
      "tools berbayar",
      "perbandingan tools",
      "AI untuk konten",
      "AI untuk riset",
    ],
    modules: [
      "Peta Tools AI Populer",
      "Memilih Tools Sesuai Kebutuhan",
      "Workflow Harian dengan Tools",
      "Integrasi Antar Tools",
    ],
  },
  {
    level: "Level 03",
    title: "AI for Professional",
    duration: "±4 jam",
    moduleCount: 7,
    lessonCount: 21,
    keywords: [
      "profesional",
      "kerja",
      "kantor",
      "produktivitas",
      "efisiensi kerja",
      "meeting",
      "notulen",
      "presentasi",
      "laporan",
      "email",
      "draft email",
      "komunikasi",
      "HR",
      "human resources",
      "rekrutmen",
      "marketing",
      "konten",
      "finance",
      "keuangan",
      "AI untuk bisnis",
      "AI untuk tim",
      "perusahaan",
      "kolaborasi",
      "manajemen",
      "manajemen tugas",
    ],
    modules: [
      "AI untuk Riset & Analisis",
      "AI untuk Menulis & Komunikasi",
      "AI untuk Presentasi & Data",
      "Etika & Kebijakan di Tempat Kerja",
    ],
  },
  {
    level: "Level 04",
    title: "AI Builder",
    duration: "±4 jam",
    moduleCount: 7,
    lessonCount: 21,
    keywords: [
      "bikin aplikasi",
      "buat aplikasi",
      "automasi",
      "otomasi",
      "workflow",
      "no-code",
      "low-code",
      "Zapier",
      "Make",
      "integrasi",
      "API",
      "deploy",
      "builder",
      "bangun produk",
      "tools custom",
      "sistem otomatis",
      "pipeline",
      "automasi tugas",
      "produktivitas",
      "efisiensi",
      "workflow otomatis",
    ],
    modules: [
      "Dasar No-Code & Otomasi",
      "Membangun Chatbot Pertama",
      "Menghubungkan API & Data",
      "Deploy Aplikasi Kecilmu",
    ],
  },
  {
    level: "Level 05",
    title: "AI Agentic",
    duration: "±4,5 jam",
    moduleCount: 7,
    lessonCount: 21,
    keywords: [
      "agent",
      "AI agent",
      "agentic",
      "autonomous",
      "mandiri",
      "self-running",
      "otomatis penuh",
      "asisten mandiri",
      "multi-step",
      "pipeline",
      "reasoning",
      "planning",
      "LangChain",
      "guardrail",
      "keamanan agent",
      "automasi",
      "otomasi",
      "workflow otomatis",
      "sistem AI",
      "AI yang berpikir sendiri",
    ],
    modules: [
      "Apa Itu AI Agent",
      "Perencanaan & Tool Use",
      "Memberi Agent Memori",
      "Menjalankan Agent Secara Otonom",
    ],
  },
  {
    level: "Level 06",
    title: "AI Orchestration",
    duration: "±5 jam",
    moduleCount: 7,
    lessonCount: 21,
    keywords: [
      "orchestration",
      "multi-agent",
      "banyak agent",
      "paralel",
      "koordinasi",
      "koordinasi AI",
      "sistem kompleks",
      "enterprise AI",
      "skala besar",
      "monitoring",
      "infrastruktur AI",
      "deployment",
      "arsitektur AI",
      "agent",
      "AI agent",
      "guardrail",
      "keamanan sistem",
      "manajemen AI",
      "tim AI",
    ],
    modules: [
      "Pola Multi-Agent",
      "Koordinasi & Antrian Tugas",
      "Observability & Guardrail",
      "Skala Produksi",
    ],
  },
];

/**
 * Case-insensitive keyword search over MENU_COURSES. A course matches when the
 * query is a substring of its title or of any keyword, or a keyword is a
 * substring of the query. Returns courses in their defined (Level) order.
 */
export function searchCourses(query) {
  const q = query.trim().toLowerCase();
  if (!q) return [];
  return MENU_COURSES.filter((course) => {
    if (course.title.toLowerCase().includes(q)) return true;
    return course.keywords.some((kw) => {
      const k = kw.toLowerCase();
      return k.includes(q) || q.includes(k);
    });
  });
}
